name: first

on: 
  push:
    branches:
      - "ch02_02"

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: | 
                  date
                  lsb_release -a 
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: |
                  date
                  systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    job3:
        name: Third job
        runs-on: macos-latest
        steps:
          - name: Step one
            uses: actions/checkout@v2
          - name: Step two
            run: |
                date
                sw_vers
    job4:
        name: Fourth job
        runs-on: ubuntu-18.04
        steps:
          - name: Step one
            uses: actions/checkout@v2
          - name: Step two
            run: |
                date
                lsb_release -a
